services:
  - type: web
    name: othello-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python servidor.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
